openapi: 3.2.0
info:
  title: Sarj.ai Voice Sip Trunk API
  version: 1.0.0
tags:
- name: SIP Trunk
paths:
  /v1/beta/sip-trunks/:
    get:
      tags:
      - SIP Trunk
      summary: List Sip Trunks
      operationId: sipTrunkListSipTrunks
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListSipTrunksResponse'
    post:
      tags:
      - SIP Trunk
      summary: Upsert Sip Trunk
      operationId: sipTrunkUpsertSipTrunk
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpsertSipTrunk'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SipTrunk'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /v1/beta/sip-trunks/{trunk_id}:
    get:
      tags:
      - SIP Trunk
      summary: Get Sip Trunk
      operationId: sipTrunkGetSipTrunk
      parameters:
      - name: trunk_id
        in: path
        required: true
        schema:
          type: string
          title: Trunk Id
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SipTrunk'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
    delete:
      tags:
      - SIP Trunk
      summary: Delete Sip Trunk
      operationId: sipTrunkDeleteSipTrunk
      parameters:
      - name: trunk_id
        in: path
        required: true
        schema:
          type: string
          title: Trunk Id
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeleteResponse'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
components:
  schemas:
    ListSipTrunksResponse:
      properties:
        items:
          items:
            $ref: '#/components/schemas/SipTrunk'
          type: array
          title: Items
      type: object
      required:
      - items
      title: ListSipTrunksResponse
    Provider:
      type: string
      enum:
      - voxa
      - bevatel
      - twilio
      - maqsam
      title: Provider
    UpsertSipTrunk:
      properties:
        id:
          anyOf:
          - type: string
          - type: 'null'
          title: Id
        trunk_id:
          type: string
          title: Trunk Id
        provider:
          $ref: '#/components/schemas/Provider'
        trunk_name:
          type: string
          title: Trunk Name
        caller_id_numbers:
          $ref: '#/components/schemas/CallerIdNumbers'
      type: object
      required:
      - trunk_id
      - provider
      - trunk_name
      - caller_id_numbers
      title: UpsertSipTrunk
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    SipTrunk:
      properties:
        id:
          type: string
          title: Id
        trunk_id:
          type: string
          title: Trunk Id
        created_at:
          type: string
          format: date-time
          title: Created At
        provider:
          $ref: '#/components/schemas/Provider'
        trunk_name:
          type: string
          title: Trunk Name
        caller_id_numbers:
          $ref: '#/components/schemas/CallerIdNumbers'
      type: object
      required:
      - id
      - trunk_id
      - created_at
      - provider
      - trunk_name
      - caller_id_numbers
      title: SipTrunk
    CallerIdNumbers:
      properties:
        numbers:
          items:
            type: string
          type: array
          title: Numbers
          default: []
      type: object
      title: CallerIdNumbers
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
        input:
          title: Input
        ctx:
          type: object
          title: Context
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
    DeleteResponse:
      properties: {}
      type: object
      title: DeleteResponse
